import React, { useState, useEffect } from 'react';
import {
  Cpu,
  Zap,
  CheckCircle2,
  AlertCircle,
  Link,
  Copy,
  Check,
  Play,
  Terminal,
  ExternalLink,
  Shield,
  Layers,
  Database
} from 'lucide-react';
import { useApp } from '../context/AppContext';

export const ColabSettings = () => {
  const { colabUrl, activeMode, saveColabConfig, colabStatus, checkColabStatus, showToast } = useApp();
  const [inputUrl, setInputUrl] = useState(colabUrl || '');
  const [selectedMode, setSelectedMode] = useState(activeMode || 'hybrid');
  const [saving, setSaving] = useState(false);
  const [copiedCode, setCopiedCode] = useState(false);

  useEffect(() => {
    setInputUrl(colabUrl || '');
    setSelectedMode(activeMode || 'hybrid');
  }, [colabUrl, activeMode]);

  const handleSave = async (e) => {
    e.preventDefault();
    setSaving(true);
    await saveColabConfig(inputUrl, selectedMode);
    setSaving(false);
  };

  const colabPythonSnippet = `!pip install -q fastapi uvicorn pyngrok pydantic
from pyngrok import ngrok
import nest_asyncio, uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

@app.post("/query")
def handle(req: dict):
    q = req.get("prompt") or req.get("query")
    return {"answer": f"⚡ [Colab LLM]: Processed inquiry '{q}' on Colab GPU!", "source": "colab_llm"}

nest_asyncio.apply()
public_url = ngrok.connect(8000).public_url
print("🚀 COLAB BACKEND LIVE URL:", public_url)
uvicorn.run(app, port=8000)`;

  const copySnippet = () => {
    navigator.clipboard.writeText(colabPythonSnippet);
    setCopiedCode(true);
    showToast('Copied Colab Python script to clipboard!', 'info');
    setTimeout(() => setCopiedCode(false), 2500);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 space-y-8">
      
      {/* Header Banner */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-white flex items-center gap-2">
            <Cpu className="w-6 h-6 text-brand-cyan" />
            Google Colab API Settings & Bridge
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Connect your live Google Colab FastAPI/Ngrok server to route bot inquiries to AI LLM inference.
          </p>
        </div>

        {/* Status Pill */}
        <div
          className={`flex items-center space-x-2 px-3.5 py-2 rounded-xl text-xs font-semibold border ${
            colabStatus.online
              ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
              : 'bg-amber-500/10 text-amber-400 border-amber-500/30'
          }`}
        >
          <span
            className={`w-2.5 h-2.5 rounded-full ${
              colabStatus.online ? 'bg-emerald-400 animate-pulse' : 'bg-amber-400'
            }`}
          ></span>
          <span>{colabStatus.online ? `Connected (${colabStatus.latency}ms)` : 'Colab Offline / Local KB active'}</span>
        </div>
      </div>

      {/* Main Settings Form */}
      <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-800 shadow-2xl space-y-6">
        <form onSubmit={handleSave} className="space-y-6">
          
          {/* Colab URL Input */}
          <div>
            <label className="block text-xs font-semibold text-slate-200 mb-2 flex items-center gap-1.5">
              <Link className="w-4 h-4 text-brand-cyan" />
              Google Colab Ngrok / Localtunnel HTTPS Endpoint URL
            </label>
            <div className="flex flex-wrap sm:flex-nowrap gap-2">
              <input
                type="url"
                value={inputUrl}
                onChange={(e) => setInputUrl(e.target.value)}
                placeholder="https://xxxx-xx-xxx-xxx-xx.ngrok-free.app"
                className="flex-1 bg-slate-900/90 border border-slate-700/80 rounded-xl px-4 py-3 text-sm font-mono text-cyan-300 placeholder-slate-600 focus:outline-none focus:border-brand-cyan"
              />
              <button
                type="button"
                onClick={checkColabStatus}
                className="px-4 py-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 transition-all flex items-center space-x-1.5 shrink-0"
              >
                <Zap className="w-4 h-4 text-brand-cyan" />
                <span>Test Ping</span>
              </button>
            </div>
            <p className="text-[11px] text-slate-400 mt-2">
              Enter the public <code className="text-cyan-400">https://</code> tunnel URL generated by Ngrok/Localtunnel inside Google Colab.
            </p>
          </div>

          {/* Mode Selection */}
          <div>
            <label className="block text-xs font-semibold text-slate-200 mb-3 flex items-center gap-1.5">
              <Layers className="w-4 h-4 text-brand-cyan" />
              Bot Routing & AI Inference Engine Mode
            </label>
            
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              
              {/* Hybrid Mode */}
              <div
                onClick={() => setSelectedMode('hybrid')}
                className={`p-4 rounded-2xl border cursor-pointer transition-all ${
                  selectedMode === 'hybrid'
                    ? 'bg-gradient-to-b from-brand-cyan/15 to-transparent border-brand-cyan shadow-lg shadow-brand-cyan/10'
                    : 'bg-slate-900/60 border-slate-800 hover:border-slate-700'
                }`}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-bold text-white flex items-center gap-1.5">
                    <Zap className="w-4 h-4 text-brand-cyan" /> Hybrid Mode
                  </span>
                  <span className="text-[9px] font-semibold px-2 py-0.5 rounded bg-brand-cyan/20 text-brand-cyan">Recommended</span>
                </div>
                <p className="text-[11px] text-slate-400 leading-relaxed">
                  Routes queries to Google Colab LLM first. Automatically falls back to local SQLite KB if Colab is offline.
                </p>
              </div>

              {/* Colab Only */}
              <div
                onClick={() => setSelectedMode('colab')}
                className={`p-4 rounded-2xl border cursor-pointer transition-all ${
                  selectedMode === 'colab'
                    ? 'bg-gradient-to-b from-brand-violet/15 to-transparent border-brand-violet shadow-lg shadow-brand-violet/10'
                    : 'bg-slate-900/60 border-slate-800 hover:border-slate-700'
                }`}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-bold text-white flex items-center gap-1.5">
                    <Cpu className="w-4 h-4 text-brand-violet" /> Colab LLM Only
                  </span>
                </div>
                <p className="text-[11px] text-slate-400 leading-relaxed">
                  Exclusively sends all chat traffic to your Google Colab backend server endpoint.
                </p>
              </div>

              {/* SQLite KB Only */}
              <div
                onClick={() => setSelectedMode('sqlite_kb')}
                className={`p-4 rounded-2xl border cursor-pointer transition-all ${
                  selectedMode === 'sqlite_kb'
                    ? 'bg-gradient-to-b from-emerald-500/15 to-transparent border-emerald-500 shadow-lg shadow-emerald-500/10'
                    : 'bg-slate-900/60 border-slate-800 hover:border-slate-700'
                }`}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-bold text-white flex items-center gap-1.5">
                    <Database className="w-4 h-4 text-emerald-400" /> SQLite KB Only
                  </span>
                </div>
                <p className="text-[11px] text-slate-400 leading-relaxed">
                  Bypasses external Colab API and uses local SQLite database knowledge base matching.
                </p>
              </div>

            </div>
          </div>

          {/* Submit Save */}
          <div className="pt-2 flex justify-end">
            <button
              type="submit"
              disabled={saving}
              className="px-6 py-3 rounded-xl bg-gradient-to-r from-brand-cyan to-blue-600 text-white text-xs font-semibold hover:opacity-90 transition-all shadow-lg shadow-brand-cyan/20 flex items-center space-x-2"
            >
              {saving ? (
                <span>Saving to SQLite...</span>
              ) : (
                <>
                  <CheckCircle2 className="w-4 h-4" />
                  <span>Save Settings to SQLite</span>
                </>
              )}
            </button>
          </div>

        </form>
      </div>

      {/* Step-by-Step Instructions & 1-Click Code Box */}
      <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-slate-800 space-y-6">
        <h3 className="text-sm font-bold text-white flex items-center gap-2">
          <Terminal className="w-4 h-4 text-brand-cyan" />
          Google Colab 3-Step Integration Guide
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
          
          <div className="bg-slate-900/80 p-4 rounded-2xl border border-slate-800 space-y-2">
            <div className="w-7 h-7 rounded-xl bg-brand-cyan/10 text-brand-cyan font-bold flex items-center justify-center border border-brand-cyan/20">
              1
            </div>
            <div className="font-semibold text-slate-200">Open Google Colab Notebook</div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Open <code className="text-cyan-300">colab/colab_enquiry_bot.ipynb</code> or upload <code className="text-cyan-300">colab/colab_server.py</code> in Google Colab.
            </p>
          </div>

          <div className="bg-slate-900/80 p-4 rounded-2xl border border-slate-800 space-y-2">
            <div className="w-7 h-7 rounded-xl bg-brand-violet/10 text-brand-violet font-bold flex items-center justify-center border border-brand-violet/20">
              2
            </div>
            <div className="font-semibold text-slate-200">Run Python FastAPI Cells</div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Execute all cells to install dependencies (<code className="text-violet-300">fastapi, pyngrok</code>) and launch the server tunnel.
            </p>
          </div>

          <div className="bg-slate-900/80 p-4 rounded-2xl border border-slate-800 space-y-2">
            <div className="w-7 h-7 rounded-xl bg-emerald-500/10 text-emerald-400 font-bold flex items-center justify-center border border-emerald-500/20">
              3
            </div>
            <div className="font-semibold text-slate-200">Copy & Connect HTTPS URL</div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Copy the generated Ngrok <code className="text-emerald-300">https://xxxx.ngrok-free.app</code> URL into the setting field above and save!
            </p>
          </div>

        </div>

        {/* 1-Click Code Box */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
              <Play className="w-3.5 h-3.5 text-brand-cyan" /> Ready-to-Paste Colab Code Snippet
            </span>
            <button
              onClick={copySnippet}
              className="flex items-center space-x-1 px-3 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium border border-slate-700 transition-all"
            >
              {copiedCode ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedCode ? 'Copied!' : 'Copy Code'}</span>
            </button>
          </div>

          <pre className="bg-slate-950 p-4 rounded-2xl text-[11px] font-mono text-cyan-300 border border-slate-800 overflow-x-auto leading-relaxed">
            {colabPythonSnippet}
          </pre>
        </div>

      </div>

    </div>
  );
};
